### ISSUE TITLE
Huge blank space after ’ character

### ISSUE THREAD

**Issue by gunchleoc** [Enigma-Game/Enigma#42]
This is the main option screen in Gàidhlig:

![enigma-options](https://user-images.githubusercontent.com/4095570/128238688-e10e55cb-12ab-4be2-af78-108fbe2bd286.png)
Looks like there's an extra em-space after each `’` character.

Enigma version: 1.30 beta

**Comment by alochmann** [comment]
This is a bug/feature in the new font (MicroHei) we are using; it disappears when switching back to, say, DejaVuSansCondensed. There are other fonts as well with similar issues, see:
  https://answers.microsoft.com/en-us/mac/forum/macoffice2016-macword/adobe-fonts-add-extra-space-after-an-apostrophe/b6b29681-aa00-4741-bc01-c8e5b855b34e
If the answer in this post is right, this is actually intentional: Chinese typography demands double width punctuation. The solution would be to use different fonts for different languages (which somewhat defeats the whole purpose of Unicode).

We will have to address this in 1.31. Until then, you can switch back to another font by changing the line "MainFont" in data/models-16.lua, data/models-32.lua, -40, -48, and -64.lua. (There are actually some lines commented out which help in the process.)

Hmm ... the extra space is only added to typesetter's apostrophe (’), not typewriter's apostrophe ('). Hence, there are three different approachs to fix this problem:
  (a) Replace all typesetter's apostrophes by typewriter's apostrophes (automatically or in the po-file).
  (b) Automatically switch fonts when switching languages.
  (c) Let the player choose the font in the options menu.
Which solution would you prefer? (They are not mutually exclusive ... one could e.g. combine (a) and (c).)

**Comment by alochmann** [comment]
Oh, or maybe there is a solution using sdl_ttf. I have to take a deep look at its options and functions.

**Comment by raoulb** [comment]
> The solution would be to use different fonts for different languages (which somewhat defeats the whole purpose of Unicode).

Not all fonts have good support for Unicode (f.e. glyphs beyond the first few 'latin' blocks in BMP). The main point of Unicode is the ability to *represent* all characters within the same encoding, *visualization* is up to the font which needs to provide the glyphs. A font with particularly good support is [Noto](https://en.wikipedia.org/wiki/Noto_fonts).

Switching fonts based on language would imo be an acceptable thing to do. (If the implementation effort is reasonable.)

**Comment by raoulb** [comment]
I'd refrain from changing actual content (e.g. switching apostrophes) as this might just shift the issue around.

**Comment by alochmann** [comment]
Raoul, I agree that permanently changing the content of the po-file should be avoided -- replacing an apostrophe on the fly when certain fonts are used might still be a viable option, but only if there are no different meanings in Scottish-Gaelic (or other languages) connected to different shapes of apostrophes ... ?

By the way: The apostrophe in question is coded in gd.po as U+2019 (RIGHT SINGLE QUOTATION MARK; 0xE28099 in UTF-8). However, when I replace it by U+02BC (MODIFIER LETTER APOSTROPHE) the output does not change.

**Comment by alochmann** [comment]
Changing the font when changing the language would need some rework of the code. Right now, the font first is defined within the lua engine (called in d_models.cc, display::InitModels), then DefineFont is called.

**Comment by gunchleoc** [comment]
How about a configuration file for the fonts, where each locale can choose one? MicroHei is a good font for CJK (Chinese Japanese Korean), DejaVu is good for Latin, Cyrillic and some more scripts, for Arabic you need yet another font. The different font sets also have different height/size requirements to appear to be of the same size/remain legible.

The only occurrence of `‘`in gd is in the translation for `Server Error: could not load level '` which is a weird string anway, so it would be easy to search/replace to get back from `'` to `’`, if you want to go with that interim solution. Let me know if you want to go that route and I can do it really quickly in my offline tool.

**Comment by alochmann** [comment]
The core problem is a decision of the Unicode committee. Character U+2019 is used as a single closing quotation mark, and at the same time as an apostrophe. These are quite obviously not the same. An interesting comment about the use of U+2019 for the English apostrophe can be found here:
  https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/

So the decision to use it as an apostrophe is technically right.

And the decision to display it as a single closing quotation mark is equally technically right.

And while two rights give a right, two technical rights give a wrong.

I therefore decided to solve this in code. For all but Chinese and Japanese, U+2019 will be replaced by the straight ASCII apostrophe during runtime, on the fly. No need to change the po-file.
