### ISSUE TITLE
Number of search results depends on sorting

### ISSUE THREAD

**Issue by double-a** [Enigma-Game/Enigma#55]
Using the search without any string entered and all default values I see 3323 levels.
Changing the sorting changes the number. 
For None, Random: 3323, Difficulty 1497, Average rating 2506 results.

I assume that this is an effect of missing rating / difficulty. Nevertheless it looks strange that the number of search results changes.
Average rating >=0.1 gives 2506 results, thus 0 should be interpreted as 'no rating'.
Difficulty >=1 gives 1497 results, thus 0 is interpreted as no value set.

**Comment by alochmann** [comment]
Yes, you are right, and this is intentional. When you press F1 on the "Search" screen, the last sentence reads: "Please note that some levels have no ratings, or no average ratings, and are therefore automatically excluded as soon as you choose to search for ratings or average ratings or sort by them."

The background is that this behaviour seems more intuitive to me. When you sort by, say, "average rating", you are obviously interested in average ratings (avr). Levels without avr are therefore omitted completely, instead of sorted to the end of the index. After all, if they were to appear at the end of the list, this would suggest that those levels are unpopular, rather than unrated.

The only alternative I see would be to not show the number of levels at all ... or am I missing an option?
