### ISSUE TITLE
Mouse leaving window

### ISSUE THREAD

**Issue by double-a** [Enigma-Game/Enigma#56]
SDL 2 works pretty fine, but sometimes I have the issue that the mouse leaves the window.
E.g. "bridge in the gap" or some labyrinth mazes...
If this happens once it happens again more often.

I noticed that after switching windows (i.e. coming back in SDL_WINDOWEVENT_FOCUS_GAINED) the RelativeMouseMode is lost. 
Unfortunately no success yet when setting it again....

**Comment by alochmann** [comment]
Hi,
thanks for pointing that out. I can replicate that bug on Linux and Windows 10 alike, and I will try to repair it for 1.31 (although it might actually turn out to be a bug within SDL 2). Please don't close this issue until then.

**Comment by SentinelProxima** [comment]
Hi, I downloaded the game today hoping to play it over discord streaming with a long-distance friend. Unfortunately this issue is making the game unplayable at the moment. I don't mean to sound pushy, but since you seem to already have plans to fix this, I hope you will let me know if you get it fixed so we can play the game together :)
